# Finds Lapack, tests, and if not found or broken, autobuild Lapack
if(lapack_external)
  include(${CMAKE_CURRENT_LIST_DIR}/lapack_external.cmake)
  return()
elseif(autobuild)
  find_package(LAPACK)
else()
  find_package(LAPACK REQUIRED)
endif()

if(LAPACK_FOUND)
  set(lapack_external false CACHE BOOL "autobuild Lapack")
else()
  include(${CMAKE_CURRENT_LIST_DIR}/lapack_external.cmake)
endif()
