# Finds Scalapack, tests, and if not found or broken, autobuild scalapack
if(scalapack_external)
  include(${CMAKE_CURRENT_LIST_DIR}/scalapack_external.cmake)
  return()
elseif(autobuild)
  find_package(SCALAPACK)
else()
  find_package(SCALAPACK REQUIRED)
endif()

if(SCALAPACK_FOUND)
  set(scalapack_external false CACHE BOOL "autobuild Scalapack")
else()
  include(${CMAKE_CURRENT_LIST_DIR}/scalapack_external.cmake)
endif()
