name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"


jobs:

  core:

    strategy:
      matrix:
        img: [
          { os: ubuntu-latest, cmd: sudo apt update && sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin liblapack-dev libscalapack-mpi-dev libmumps-dev libparmetis-dev },
          { os: macos-latest, cmd: brew install scalapack open-mpi metis && brew reinstall gcc}
          ]

    runs-on: ${{ matrix.img.os }}

    steps:

    - uses: actions/checkout@v3

    - name: Install packages
      run: ${{ matrix.img.cmd }}

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build -V
