name: ci_meson

on:
  push:
    paths:
      - "**/meson.build"
      - ".github/workflows/ci_meson.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - name: Install packages
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libopenmpi-dev openmpi-bin liblapack-dev libscalapack-openmpi-dev libmumps-dev libparmetis-dev

    - run: meson setup build
      env:
        FC: gfortran

    - run: meson compile -C build

    - run: meson test -C build -v


  macos:
    needs: linux
    runs-on: macos-latest
    env:
        FC: gfortran-11

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: brew install ninja scalapack

    - run: pip install meson

    - run: meson setup build

    - run: meson compile -C build

    - run: meson test -C build -v
